# Dracula
COLOR_BG=282a36
COLOR_SURFACE=343746
COLOR_OVERLAY=44475a
COLOR_BORDER=6272a4
COLOR_SELECTION=44475a
COLOR_CURSOR_LINE=2f3240
COLOR_FG=f8f8f2
COLOR_FG_SUBTLE=bfbfbf
COLOR_FG_MUTED=6272a4
COLOR_RED=ff5555
COLOR_ROSE=ffb86c
COLOR_GOLD=f1fa8c
COLOR_PINE=8be9fd
COLOR_FOAM=50fa7b
COLOR_IRIS=bd93f9
COLOR_BLACK=282a36
COLOR_RED_N=ff5555
COLOR_GREEN_N=50fa7b
COLOR_YELLOW_N=f1fa8c
COLOR_BLUE_N=8be9fd
COLOR_MAGENTA_N=ff79c6
COLOR_CYAN_N=8be9fd
COLOR_WHITE_N=f8f8f2
COLOR_BRIGHT_BLACK=6272a4
COLOR_BRIGHT_RED=ff5555
COLOR_BRIGHT_GREEN=50fa7b
COLOR_BRIGHT_YELLOW=f1fa8c
COLOR_BRIGHT_BLUE=8be9fd
COLOR_BRIGHT_MAGENTA=ff79c6
COLOR_BRIGHT_CYAN=8be9fd
COLOR_BRIGHT_WHITE=f8f8f2
COLOR_DIM_BLACK=21222c
COLOR_DIM_RED=bfbfbf
COLOR_DIM_GREEN=50fa7b
COLOR_DIM_YELLOW=f1fa8c
COLOR_DIM_BLUE=8be9fd
COLOR_DIM_MAGENTA=ff79c6
COLOR_DIM_CYAN=8be9fd
COLOR_DIM_WHITE=6272a4
