# Rosé Pine
COLOR_BG=191724
COLOR_SURFACE=1f1d2e
COLOR_OVERLAY=26233a
COLOR_BORDER=524f67
COLOR_SELECTION=403d52
COLOR_CURSOR_LINE=21202e
COLOR_FG=e0def4
COLOR_FG_SUBTLE=908caa
COLOR_FG_MUTED=6e6a86
COLOR_RED=eb6f92
COLOR_ROSE=ebbcba
COLOR_GOLD=f6c177
COLOR_PINE=31748f
COLOR_FOAM=9ccfd8
COLOR_IRIS=c4a7e7
COLOR_BLACK=191724
COLOR_RED_N=eb6f92
COLOR_GREEN_N=9ccfd8
COLOR_YELLOW_N=f6c177
COLOR_BLUE_N=31748f
COLOR_MAGENTA_N=c4a7e7
COLOR_CYAN_N=9ccfd8
COLOR_WHITE_N=e0def4
COLOR_BRIGHT_BLACK=6e6a86
COLOR_BRIGHT_RED=eb6f92
COLOR_BRIGHT_GREEN=9ccfd8
COLOR_BRIGHT_YELLOW=f6c177
COLOR_BRIGHT_BLUE=31748f
COLOR_BRIGHT_MAGENTA=c4a7e7
COLOR_BRIGHT_CYAN=9ccfd8
COLOR_BRIGHT_WHITE=e0def4
COLOR_DIM_BLACK=16141f
COLOR_DIM_RED=908caa
COLOR_DIM_GREEN=9ccfd8
COLOR_DIM_YELLOW=f6c177
COLOR_DIM_BLUE=31748f
COLOR_DIM_MAGENTA=c4a7e7
COLOR_DIM_CYAN=9ccfd8
COLOR_DIM_WHITE=6e6a86
