# Rosé Pine Moon
COLOR_BG=232136
COLOR_SURFACE=2a273f
COLOR_OVERLAY=393552
COLOR_BORDER=56526e
COLOR_SELECTION=44415a
COLOR_CURSOR_LINE=2a283e
COLOR_FG=e0def4
COLOR_FG_SUBTLE=908caa
COLOR_FG_MUTED=6e6a86
COLOR_RED=eb6f92
COLOR_ROSE=ea9a97
COLOR_GOLD=f6c177
COLOR_PINE=3e8fb0
COLOR_FOAM=9ccfd8
COLOR_IRIS=c4a7e7
COLOR_BLACK=232136
COLOR_RED_N=eb6f92
COLOR_GREEN_N=9ccfd8
COLOR_YELLOW_N=f6c177
COLOR_BLUE_N=3e8fb0
COLOR_MAGENTA_N=c4a7e7
COLOR_CYAN_N=9ccfd8
COLOR_WHITE_N=e0def4
COLOR_BRIGHT_BLACK=6e6a86
COLOR_BRIGHT_RED=eb6f92
COLOR_BRIGHT_GREEN=9ccfd8
COLOR_BRIGHT_YELLOW=f6c177
COLOR_BRIGHT_BLUE=3e8fb0
COLOR_BRIGHT_MAGENTA=c4a7e7
COLOR_BRIGHT_CYAN=9ccfd8
COLOR_BRIGHT_WHITE=e0def4
COLOR_DIM_BLACK=1f1d2e
COLOR_DIM_RED=908caa
COLOR_DIM_GREEN=9ccfd8
COLOR_DIM_YELLOW=f6c177
COLOR_DIM_BLUE=3e8fb0
COLOR_DIM_MAGENTA=c4a7e7
COLOR_DIM_CYAN=9ccfd8
COLOR_DIM_WHITE=6e6a86
