# ~/.config/hypr/hypridle.conf
general {
  lock_cmd = pidof hyprlock || ~/.config/niri/scripts/lock.sh
  before_sleep_cmd = ~/.config/niri/scripts/lock.sh
  after_sleep_cmd = niri msg action power-on-monitors
  ignore_dbus_inhibit = false
}

listener {
  timeout = 300
  on-timeout = niri msg action power-off-monitors
  on-resume = niri msg action power-on-monitors
}

listener {
  timeout = 600
  on-timeout = ~/.config/niri/scripts/lock.sh
}

