cursor #d7e5e7
cursor_text_color #bbc9cb

foreground            #d7e5e7
background            #091517
selection_foreground  #073543
selection_background  #a5ccde
url_color             #00dbee

color0   #091517
color1   #ff0059
color2   #00ee15
color3   #ffed00
color4   #00d0e2
color5   #00656e
color6   #00dbee
color7   #dbf7f9
color8   #83989a
color9   #ff3f82
color10  #4cff5c
color11  #fff24c
color12  #26edff
color13  #4cf0ff
color14  #8cf5ff
color15  #f2fdff
