cursor #d9e4ea
cursor_text_color #bdc8ce

foreground            #d9e4ea
background            #0a1519
selection_foreground  #133348
selection_background  #accae5
url_color             #57d5ff

color0   #0a1519
color1   #ff4683
color2   #57ff68
color3   #fff346
color4   #32c2f2
color5   #005876
color6   #57d5ff
color7   #eaf9ff
color8   #95a1a5
color9   #ff81aa
color10  #89ff95
color11  #fff789
color12  #70dbff
color13  #89e1ff
color14  #b3ecff
color15  #f6fcff
