cursor #d7e5e6
cursor_text_color #bbc9ca

foreground            #d7e5e6
background            #091516
selection_foreground  #043542
selection_background  #a4cddc
url_color             #00dbe8

color0   #091516
color1   #ff005a
color2   #00e814
color3   #ffec00
color4   #00d0dc
color5   #00656b
color6   #00dbe8
color7   #d6f1f3
color8   #809596
color9   #ff3f83
color10  #4cff5c
color11  #fff24c
color12  #26f2ff
color13  #4cf4ff
color14  #8cf8ff
color15  #f2feff
