bind=SUPER+CTRL+ALT,t,spawn,dms ipc call wallpaper next # Wallpaper: Next
bind=SUPER+CTRL,t,spawn,dms ipc call dankdash wallpaper # Wallpaper Browser
bind=SUPER,a,spawn,dms ipc call control-center toggle # Control Center
bind=SUPER,d,spawn,dms ipc call spotlight toggle # Launcher
bind=SUPER,h,spawn,dms ipc call inhibit toggle # Idle Inhibit: Toggle
bind=SUPER,i,spawn,dms ipc call settings toggle # Settings
bind=SUPER,l,spawn,dms ipc call lockscreen lock # Lock Screen
bind=SUPER,n,spawn,dms ipc call dash open overview # Dashboard: Overview
bind=SUPER,v,spawn,dms ipc call clipboard toggle # Clipboard
bind=none,XF86AudioNext,spawn,dms ipc call mpris next # Media: Next Track
bind=none,XF86AudioPause,spawn,dms ipc call mpris playPause # Media: Play/Pause
bind=none,XF86AudioPlay,spawn,dms ipc call mpris playPause # Media: Play/Pause
bind=none,XF86AudioPrev,spawn,dms ipc call mpris previous # Media: Previous Track
